# Generated by Django 6.0.2 on 2026-02-16 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('hr_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('industry_type', models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance & Banking'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail & E-commerce'), ('CONSULTING', 'Consulting'), ('STARTUP', 'Startup'), ('OTHER', 'Other')], max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 1-50, 51-200, 201-500, 500+', max_length=50, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
